/** Lender case view copy (Spanish). */

export const KPI_LABEL: Record<string, string> = {
  revenue: "Cifra de negocios",
  ebitda: "EBITDA",
  ebitdaMargin: "Margen EBITDA",
  currentRatio: "Liquidez",
  quickRatio: "Prueba ácida",
  workingCapital: "Fondo de maniobra",
  financialDebt: "Deuda financiera",
  netDebt: "Deuda financiera neta",
  netDebtToEbitda: "DFN / EBITDA",
  debtToEquity: "Deuda / patrimonio",
  interestCoverage: "Cobertura int.",
  dscr: "DSCR",
  dso: "DSO",
  dpo: "DPO",
  ebitCoverage: "Cobertura de intereses con EBIT",
  debtToEbitda: "Deuda financiera / EBITDA",
  liabilitiesToEquity: "Pasivo total / patrimonio",
  grossMargin: "Margen bruto",
  netMargin: "Margen neto",
  roa: "Rentabilidad del activo (ROA)",
  roe: "Rentabilidad del patrimonio (ROE)",
  dio: "Días de existencias (DIO)",
  ccc: "Ciclo de conversión de caja",
  assetTurnover: "Rotación del activo",
  minBalance: "Saldo mínimo",
  averageDailyBalance: "Saldo medio diario",
  currentToAverage: "Saldo actual / saldo medio 90 días",
  daysCashOnHand: "Días de caja",
  operatingCashFlow: "Flujo de caja operativo (mes)",
  netBurn: "Consumo neto (mes)",
  inflowOutflowRatio: "Entradas / salidas 90 días",
  inflowVolatility: "Volatilidad de los cobros mensuales",
  receiptsPerMonth: "Cobros de clientes por mes",
  debtServiceBurden: "Carga de deuda sobre cobros",
  payrollRegularity: "Regularidad de las nóminas",
  returnedItems: "Devoluciones e impagos",
  overdraftDays: "Días en descubierto",
  returnedReceiptsRatio: "Recibos de clientes devueltos",
  publicInflowShare: "Devoluciones de Hacienda y Seguridad Social",
  internalTransferShare: "Traspasos entre cuentas propias",
};

/** Labels for KPI inputs and check evidence values. Unknown keys fall back to the raw key. */
export const VALUE_LABEL: Record<string, string> = {
  revenue: "Cifra de negocios",
  months: "Meses",
  operatingResult: "Resultado de explotación",
  depreciation: "Amortización",
  operatingImpairments: "Deterioros de explotación",
  nonRecurringResult: "Resultados excepcionales",
  grantsTransferred: "Subvenciones",
  ebitda: "EBITDA",
  netDebt: "Deuda financiera neta",
  ebitdaAnnualised: "EBITDA anualizado",
  interestAnnualised: "Intereses anualizados",
  principal: "Principal a 12 meses",
  tradeReceivables: "Clientes",
  revenueAnnualised: "Ventas anualizadas",
  vatRate: "IVA",
  tradePayables: "Proveedores",
  purchasesAnnualised: "Compras anualizadas",
  currentAssets: "Activo corriente",
  currentLiabilities: "Pasivo corriente",
  inventories: "Existencias",
  longTerm: "Deuda a largo plazo",
  shortTerm: "Deuda a corto plazo",
  financialDebt: "Deuda financiera",
  cash: "Tesorería",
  shortTermInvestments: "Inversiones a corto plazo",
  equity: "Patrimonio neto",
  cirbeDrawn: "Dispuesto CIRBE",
  operatingResultAnnualised: "Resultado de explotación anualizado",
  cogs: "Aprovisionamientos",
  cogsAnnualised: "Aprovisionamientos anualizados",
  netIncome: "Resultado del periodo",
  netIncomeAnnualised: "Resultado anualizado",
  totalAssets: "Activo total",
  totalLiabilities: "Pasivo total",
  dsoDays: "DSO (días)",
  dioDays: "DIO (días)",
  dpoDays: "DPO (días)",
  // bank KPIs
  days: "Días",
  recentDays: "Días recientes",
  fullMonths: "Meses completos",
  closingBalance: "Saldo final",
  averageBalance90d: "Saldo medio 90 días",
  operatingOutflows: "Pagos operativos",
  receipts: "Cobros de clientes",
  returnedReceipts: "Recibos de clientes devueltos",
  burnMonths: "Meses con flujo negativo",
  inflows90d: "Entradas 90 días",
  outflows90d: "Salidas 90 días",
  meanMonthlyReceipts: "Cobro medio mensual",
  stdDevMonthlyReceipts: "Desviación típica mensual",
  receiptCount: "Número de cobros",
  debtService: "Cuotas de deuda",
  interestPaid: "Intereses pagados",
  netReceipts: "Cobros netos",
  monthsWithPayroll: "Meses con nóminas",
  payrollTotal: "Nóminas pagadas",
  returnedReceiptCount: "Recibos de clientes devueltos (n.º)",
  returnedDebitCount: "Recibos propios devueltos (n.º)",
  identifiedReceipts: "Cobros de clientes identificados",
  publicRefunds: "Devoluciones públicas",
  bankInflows: "Entradas (sin traspasos)",
  internalTransfers: "Traspasos propios recibidos",
  totalInflows: "Total de entradas",
  // check evidence
  cirbe_drawn: "Dispuesto CIRBE",
  books_financial_debt: "Deuda financiera en libros",
  difference: "Diferencia",
  cirbe_as_of: "Fecha CIRBE",
  statement_period_end: "Cierre contable comparado",
  overdue: "Vencido / dudoso",
  bank_inflows: "Cobros bancarios",
  identified_receipts: "Cobros de clientes identificados",
  unclassified_inflows: "Ingresos sin clasificar (contados)",
  returned_receipts: "Recibos devueltos (restados)",
  total_bank_inflows: "Total ingresos en banco",
  excluded_internal_transfer: "Traspasos entre cuentas propias (no cuentan)",
  excluded_financing: "Préstamos y pólizas (no cuentan)",
  excluded_trade_finance: "Anticipos, factoring y descuento (no cuentan)",
  excluded_equity: "Aportaciones de socios (no cuentan)",
  excluded_refund: "Devoluciones (no cuentan)",
  excluded_investment_income: "Inversiones y depósitos (no cuentan)",
  excluded_reversal: "Anulaciones (no cuentan)",
  financing_inflows: "Préstamos y pólizas dispuestos",
  trade_finance_inflows: "Anticipos, factoring y descuento",
  expected_from_revenue: "Ventas con IVA del periodo",
  overlap_start: "Desde",
  overlap_end: "Hasta",
  overlap_months: "Meses comparados",
  vat_rate: "IVA",
  ratio: "Ratio",
  modelo200: "Modelo 200",
  modelo303: "Modelo 303",
  declared_sales: "Ventas declaradas en IVA",
  period_start: "Desde",
  period_end: "Hasta",
  returns: "Declaraciones",
  books: "Contabilidad",
  fiscal_year: "Ejercicio",
  issued_on: "Emitido",
  valid_until: "Válido hasta",
  result: "Resultado",
  max_age_days: "Antigüedad máxima (días)",
  age_days: "Antigüedad (días)",
  verification_code: "CSV",
  debt_payments: "Pagos de deuda",
  months_with_payments: "Meses con pagos",
  cirbe_drawn_total: "Dispuesto CIRBE",
  accounts: "Cuentas",
  debit: "Debe",
  credit: "Haber",
  diff: "Diferencia",
  start: "Desde",
  account: "Cuenta",
  amount: "Importe",
  net: "Saldo",
  end: "Hasta",
  sheet: "Hoja registral",
  act_date: "Fecha del acto",
  act: "Acto",
  acts: "Actos publicados",
  resulting_capital: "Capital resultante",
  changes: "Cambios",
  from: "Desde",
  first_seen: "Primer acto importado",
  provider: "Proveedor",
  report_date: "Fecha del informe",
  incidents: "Incidencias",
  report: "Informe",
};

/** Short labels for passing checks, shown as green pills. */
export const CHECK_PASS_LABEL: Record<string, string> = {
  cirbe_vs_books_debt: "CIRBE cuadra con libros",
  cirbe_overdue: "CIRBE sin impagos",
  n43_inflows_vs_revenue: "Cobros coherentes con ventas",
  n43_overdrawn: "Sin descubiertos",
  n43_debt_payments_vs_declared: "Pagos de deuda declarados",
  n43_financing_inflows: "Financiación declarada",
  m200_vs_books_revenue: "Modelo 200: ventas cuadran",
  m200_vs_books_netIncome: "Modelo 200: resultado cuadra",
  m200_vs_books_equity: "Modelo 200: patrimonio cuadra",
  m303_quarters: "Modelo 303: 4 trimestres",
  m303_vs_books_revenue: "Modelo 303: ventas cuadran",
  aeat_cert_valid: "Certificado AEAT vigente",
  tgss_cert_valid: "Certificado TGSS vigente",
  borme_no_adverse_acts: "BORME sin actos adversos",
  solvency_payment_incidents: "Sin incidencias de pago",
  solvency_judicial: "Sin incidencias judiciales",
  solvency_vs_books_revenue: "Informe de solvencia: ventas cuadran",
};

/** Name of each check, for the evidence panel header. */
export const CHECK_NAME: Record<string, string> = {
  cirbe_vs_books_debt: "Deuda CIRBE vs contabilidad",
  cirbe_overdue: "Riesgo vencido en CIRBE",
  n43_inflows_vs_revenue: "Cobros bancarios vs ventas",
  n43_overdrawn: "Descubiertos bancarios",
  n43_debt_payments_vs_declared: "Pagos de deuda vs deuda declarada",
  n43_financing_inflows: "Entradas de financiación en bancos",
  m200_vs_books_revenue: "Modelo 200 vs libros · ventas",
  m200_vs_books_netIncome: "Modelo 200 vs libros · resultado",
  m200_vs_books_equity: "Modelo 200 vs libros · patrimonio",
  m303_quarters: "Modelo 303 · últimos 4 trimestres",
  m303_vs_books_revenue: "Modelo 303 vs libros · ventas",
  m200_total_assets_mismatch: "Modelo 200: total activo no cuadra",
  m200_total_liabilities_mismatch: "Modelo 200: total pasivo no cuadra",
  m200_pre_tax_mismatch: "Modelo 200: resultado antes de impuestos no cuadra",
  m200_lines_exceed_total: "Modelo 200: partidas por encima del total",
  m200_operating_lines_unreconciled: "Modelo 200: partidas de explotación sin identificar",
  m200_discontinued_operations: "Modelo 200: operaciones interrumpidas",
  aeat_cert_valid: "Certificado AEAT",
  tgss_cert_valid: "Certificado TGSS",
  overdrawn_bank_account: "Cuenta bancaria con saldo acreedor",
  balance_sheet_imbalance: "Balance descuadrado",
  ca_total_assets_mismatch: "Cuentas anuales: total activo no cuadra",
  ca_total_liabilities_mismatch: "Cuentas anuales: total pasivo no cuadra",
  ca_pre_tax_mismatch: "Cuentas anuales: resultado antes de impuestos no cuadra",
  ca_lines_exceed_total: "Cuentas anuales: partidas por encima del total",
  ca_operating_lines_unreconciled: "Cuentas anuales: partidas de explotación sin identificar",
  ca_discontinued_operations: "Cuentas anuales: operaciones interrumpidas",
  ca_incomplete: "Cuentas anuales incompletas",
  pnl_unavailable: "Sin cuenta de resultados",
  unmapped_account: "Cuenta sin mapeo PGC",
  tb_unbalanced: "Sumas y saldos descuadrado",
  tb_period_assumed: "Periodo supuesto",
  holded_closing_entries_suspected: "Posible asiento de cierre",
  holded_tb_unbalanced: "Holded: sumas y saldos descuadrado",
  holded_opening_reconstructed: "Holded: apertura reconstruida",
  holded_chart_mismatch: "Holded: plan de cuentas vs diario",
  n43_pdf_pending: "Extractos en PDF sin leer",
  borme_insolvency: "BORME · situación concursal",
  borme_dissolution: "BORME · disolución o extinción",
  borme_sheet_closed: "BORME · hoja registral cerrada",
  borme_capital_reduction: "BORME · reducción de capital",
  borme_officer_turnover: "BORME · cambios de administradores",
  borme_address_change: "BORME · cambio de domicilio",
  borme_recent_incorporation: "BORME · sociedad reciente",
  borme_no_adverse_acts: "BORME · sin actos adversos",
  solvency_payment_incidents: "Informe de solvencia · incidencias de pago",
  solvency_judicial: "Informe de solvencia · incidencias judiciales",
  solvency_vs_books_revenue: "Informe de solvencia vs libros · ventas",
};

export const SEVERITY_LABEL = { high: "Alta", warn: "Media", info: "Info" } as const;

export const REVIEW_LABEL = { open: "Abierta", reviewed: "Revisada", clarification_requested: "Aclaración pedida" } as const;

export const DOC_KIND_LABEL: Record<string, string> = {
  trial_balance: "Sumas y saldos",
  norma43: "Norma 43",
  modelo200: "Modelo 200",
  modelo303: "Modelo 303",
  cuentas_anuales: "Cuentas anuales",
  cirbe: "CIRBE",
  aeat_cert: "Certificado AEAT",
  tgss_cert: "Certificado TGSS",
  solvency_report: "Informe de solvencia",
  borme: "BORME",
  other: "Documento",
};

export const DISCLAIMER = "credIA verifica y organiza la información; no puntúa ni recomienda. La decisión es del prestamista.";

/** Activity (audit log) labels for the Detalles sheet. Unknown actions show their code. */
export const AUDIT_LABEL: Record<string, string> = {
  "case.created": "Caso creado",
  "borrower.invited": "Enlace enviado a la empresa",
  "borrower.link_regenerated": "Nuevo enlace generado",
  "case.viewed_as_borrower": "Vista de la empresa consultada",
  "document.uploaded": "Documento subido",
  "document.requested": "Documento pedido a la empresa",
  "delegate.invited": "Enlace enviado a la gestoría",
  "holded.connected": "Holded conectado",
  "holded.synced": "Holded sincronizado",
  "holded.sync_failed": "Error al sincronizar Holded",
  "holded.token_deleted": "Clave de Holded eliminada",
  "holded.token_discarded": "Clave de Holded descartada",
  "case.submitted": "Documentación enviada",
  "consent.withdrawn": "Consentimiento retirado",
  "support.requested": "La empresa pidió ayuda",
  "pipeline.recomputed": "Datos recalculados",
  "check.reviewed": "Alerta marcada como revisada",
  "check.clarification_requested": "Aclaración pedida",
  "check.open": "Alerta reabierta",
  "package.exported": "Paquete exportado",
  "document.downloaded": "Documento abierto",
  "support.closed": "Petición de ayuda atendida",
  "case.viewed": "Caso consultado",
  "case.tables_viewed": "Tablas completas consultadas",
  "borme.match_confirmed": "Empresa confirmada en el BORME",
  "borme.match_none": "Empresa no encontrada en el BORME",
  "borme.match_clear": "Empresa del BORME por confirmar de nuevo",
  "borme.new_acts": "Nuevos actos en el BORME",
};

export const ACTOR_LABEL: Record<string, string> = { borrower: "Empresa", delegate: "Gestoría", system: "Sistema" };

/** Canonical statement lines (PGC roll-up), for the full tables and exports. */
export const LINE_LABEL: Record<string, string> = {
  nonCurrentAssets: "Activo no corriente",
  inventories: "Existencias",
  tradeReceivables: "Clientes",
  otherReceivables: "Otros deudores",
  shortTermInvestments: "Inversiones financieras a corto plazo",
  cash: "Tesorería",
  prepayments: "Periodificaciones",
  totalAssets: "Total activo",
  equity: "Patrimonio neto",
  currentYearResultIncluded: "  del que resultado del periodo (sin cerrar)",
  provisions: "Provisiones",
  longTermFinancialDebt: "Deuda financiera a largo plazo",
  longTermOtherLiabilities: "Otros pasivos a largo plazo",
  shortTermFinancialDebt: "Deuda financiera a corto plazo",
  relatedPartyShortTerm: "Deudas con socios y vinculadas",
  tradePayables: "Proveedores",
  otherCurrentLiabilities: "Otros pasivos corrientes",
  totalLiabilities: "Total patrimonio neto y pasivo",
  revenue: "Cifra de negocios",
  otherOperatingIncome: "Otros ingresos de explotación",
  cogs: "Aprovisionamientos",
  personnel: "Gastos de personal",
  externalServices: "Servicios exteriores",
  otherTaxes: "Tributos",
  otherOperatingExpenses: "Otros gastos de explotación",
  grantsTransferred: "Imputación de subvenciones",
  nonRecurringResult: "Resultados excepcionales",
  ebitda: "EBITDA",
  depreciation: "Amortización",
  operatingImpairments: "Deterioros de explotación",
  operatingResult: "Resultado de explotación",
  financialIncome: "Ingresos financieros",
  financialExpense: "Gastos financieros",
  financialImpairments: "Deterioros financieros",
  financialResult: "Resultado financiero",
  preTaxResult: "Resultado antes de impuestos",
  incomeTax: "Impuesto sobre beneficios",
  netIncome: "Resultado del periodo",
};

/** KPI tiles the «Indicadores» module can show (its settings in the panel designer). */
export const KPI_TILE_LABEL: Record<string, string> = {
  dscr: "DSCR",
  interestCoverage: "Cobertura de intereses",
  netDebtToEbitda: "DFN / EBITDA",
  currentRatio: "Liquidez",
  dsoDpo: "DSO / DPO",
  revenue: "Cifra de negocios",
  ebitda: "EBITDA y margen",
  debtToEquity: "Deuda / patrimonio",
  workingCapital: "Fondo de maniobra",
  financialDebt: "Deuda financiera",
  grossMargin: "Margen bruto",
  netMargin: "Margen neto",
  roe: "ROE y ROA",
  ebitCoverage: "Cobertura de intereses con EBIT",
  debtToEbitda: "Deuda financiera / EBITDA",
  liabilitiesToEquity: "Pasivo total / patrimonio",
  ccc: "Ciclo de conversión de caja",
  assetTurnover: "Rotación del activo",
  // from the bank movements
  minBalance: "Saldo mínimo (12 meses)",
  averageDailyBalance: "Saldo medio diario",
  currentToAverage: "Saldo actual frente al medio (90 días)",
  daysCashOnHand: "Días de caja",
  operatingCashFlow: "Flujo de caja operativo al mes",
  netBurn: "Consumo neto en meses negativos",
  inflowOutflowRatio: "Entradas frente a salidas (90 días)",
  inflowVolatility: "Volatilidad de los cobros",
  receiptsPerMonth: "Cobros de clientes al mes",
  debtServiceBurden: "Carga de deuda sobre cobros",
  payrollRegularity: "Regularidad de las nóminas",
  returnedItems: "Devoluciones e impagos",
  overdraftDays: "Días en descubierto",
  returnedReceiptsRatio: "Recibos de clientes devueltos",
  publicInflowShare: "Devoluciones de Hacienda y Seg. Social",
  internalTransferShare: "Traspasos entre cuentas propias",
};

/** Groups of the KPI tile catalogue in the panel designer. */
export const KPI_TILE_GROUP_LABEL: Record<"accounting" | "bank", string> = {
  accounting: "De la contabilidad",
  bank: "De los extractos bancarios",
};

/** Figures the «Resumen» sentence can state (its settings in the panel designer). */
export const SUMMARY_FACT_LABEL: Record<string, string> = {
  revenue: "Ventas",
  ebitda: "EBITDA y margen",
  cirbe: "Deuda CIRBE frente a libros",
  netIncome: "Resultado neto",
  ytdRevenue: "Ventas del año en curso",
  netDebt: "Deuda financiera neta",
  equity: "Patrimonio neto",
  workingCapital: "Fondo de maniobra",
};

export const PERIOD_CHOICE_LABEL = { base: "Periodo base", closed: "Ejercicio cerrado", ytd: "Año en curso" } as const;

/** What a bank movement is (src/lib/bank/classify.ts), for evidence and tables. */
export const BANK_CATEGORY_LABEL: Record<string, string> = {
  customer_receipt: "Cobros de clientes",
  trade_finance: "Anticipos, factoring y descuento",
  financing: "Préstamos y pólizas",
  equity: "Aportaciones de socios",
  refund: "Devoluciones recibidas",
  investment_income: "Inversiones y depósitos",
  other_inflow: "Ingresos sin clasificar",
  operating_payment: "Pagos operativos",
  payroll: "Nóminas",
  social_security: "Seguridad Social",
  tax: "Impuestos",
  debt_service: "Cuotas de préstamos y leasing",
  interest: "Intereses",
  bank_fees: "Comisiones bancarias",
  cash_withdrawal: "Retiradas de efectivo",
  customer_return: "Recibos devueltos",
  distribution: "Dividendos y reparto",
  investment: "Inversiones",
  other_outflow: "Pagos sin clasificar",
  internal_transfer: "Traspasos entre cuentas propias",
  reversal: "Anulaciones",
};
