/** Lender case view copy (Spanish). */

export const KPI_LABEL: Record<string, string> = {
  revenue: "Cifra de negocios",
  ebitda: "EBITDA",
  ebitdaMargin: "Margen EBITDA",
  currentRatio: "Liquidez",
  quickRatio: "Prueba ácida",
  workingCapital: "Fondo de maniobra",
  financialDebt: "Deuda financiera",
  netDebt: "Deuda financiera neta",
  netDebtToEbitda: "DFN / EBITDA",
  debtToEquity: "Deuda / patrimonio",
  interestCoverage: "Cobertura int.",
  dscr: "DSCR",
  dso: "DSO",
  dpo: "DPO",
};

/** Labels for KPI inputs and check evidence values. Unknown keys fall back to the raw key. */
export const VALUE_LABEL: Record<string, string> = {
  revenue: "Cifra de negocios",
  months: "Meses",
  operatingResult: "Resultado de explotación",
  depreciation: "Amortización",
  operatingImpairments: "Deterioros de explotación",
  nonRecurringResult: "Resultados excepcionales",
  grantsTransferred: "Subvenciones",
  ebitda: "EBITDA",
  netDebt: "Deuda financiera neta",
  ebitdaAnnualised: "EBITDA anualizado",
  interestAnnualised: "Intereses anualizados",
  principal: "Principal a 12 meses",
  tradeReceivables: "Clientes",
  revenueAnnualised: "Ventas anualizadas",
  vatRate: "IVA",
  tradePayables: "Proveedores",
  purchasesAnnualised: "Compras anualizadas",
  currentAssets: "Activo corriente",
  currentLiabilities: "Pasivo corriente",
  inventories: "Existencias",
  longTerm: "Deuda a largo plazo",
  shortTerm: "Deuda a corto plazo",
  financialDebt: "Deuda financiera",
  cash: "Tesorería",
  shortTermInvestments: "Inversiones a corto plazo",
  equity: "Patrimonio neto",
  cirbeDrawn: "Dispuesto CIRBE",
  // check evidence
  cirbe_drawn: "Dispuesto CIRBE",
  books_financial_debt: "Deuda financiera en libros",
  difference: "Diferencia",
  cirbe_as_of: "Fecha CIRBE",
  statement_period_end: "Cierre contable comparado",
  overdue: "Vencido / dudoso",
  bank_inflows: "Cobros bancarios",
  expected_from_revenue: "Ventas con IVA del periodo",
  overlap_start: "Desde",
  overlap_end: "Hasta",
  overlap_months: "Meses comparados",
  vat_rate: "IVA",
  ratio: "Ratio",
  modelo200: "Modelo 200",
  books: "Contabilidad",
  fiscal_year: "Ejercicio",
  issued_on: "Emitido",
  valid_until: "Válido hasta",
  result: "Resultado",
  max_age_days: "Antigüedad máxima (días)",
  age_days: "Antigüedad (días)",
  verification_code: "CSV",
  debt_payments: "Pagos de deuda",
  months_with_payments: "Meses con pagos",
  cirbe_drawn_total: "Dispuesto CIRBE",
  accounts: "Cuentas",
  debit: "Debe",
  credit: "Haber",
  diff: "Diferencia",
  start: "Desde",
  account: "Cuenta",
  amount: "Importe",
  net: "Saldo",
  end: "Hasta",
};

/** Short labels for passing checks, shown as green pills. */
export const CHECK_PASS_LABEL: Record<string, string> = {
  cirbe_vs_books_debt: "CIRBE cuadra con libros",
  cirbe_overdue: "CIRBE sin impagos",
  n43_inflows_vs_revenue: "Cobros coherentes con ventas",
  n43_overdrawn: "Sin descubiertos",
  n43_debt_payments_vs_declared: "Pagos de deuda declarados",
  m200_vs_books_revenue: "Modelo 200: ventas cuadran",
  m200_vs_books_netIncome: "Modelo 200: resultado cuadra",
  m200_vs_books_equity: "Modelo 200: patrimonio cuadra",
  aeat_cert_valid: "Certificado AEAT vigente",
  tgss_cert_valid: "Certificado TGSS vigente",
};

/** Name of each check, for the evidence panel header. */
export const CHECK_NAME: Record<string, string> = {
  cirbe_vs_books_debt: "Deuda CIRBE vs contabilidad",
  cirbe_overdue: "Riesgo vencido en CIRBE",
  n43_inflows_vs_revenue: "Cobros bancarios vs ventas",
  n43_overdrawn: "Descubiertos bancarios",
  n43_debt_payments_vs_declared: "Pagos de deuda vs deuda declarada",
  m200_vs_books_revenue: "Modelo 200 vs libros · ventas",
  m200_vs_books_netIncome: "Modelo 200 vs libros · resultado",
  m200_vs_books_equity: "Modelo 200 vs libros · patrimonio",
  aeat_cert_valid: "Certificado AEAT",
  tgss_cert_valid: "Certificado TGSS",
  overdrawn_bank_account: "Cuenta bancaria con saldo acreedor",
  balance_sheet_imbalance: "Balance descuadrado",
  pnl_unavailable: "Sin cuenta de resultados",
  unmapped_account: "Cuenta sin mapeo PGC",
  tb_unbalanced: "Sumas y saldos descuadrado",
  tb_period_assumed: "Periodo supuesto",
  holded_closing_entries_suspected: "Posible asiento de cierre",
  holded_tb_unbalanced: "Holded: sumas y saldos descuadrado",
  holded_opening_reconstructed: "Holded: apertura reconstruida",
  holded_chart_mismatch: "Holded: plan de cuentas vs diario",
  n43_pdf_pending: "Extractos en PDF sin leer",
};

export const SEVERITY_LABEL = { high: "Alta", warn: "Media", info: "Info" } as const;

export const REVIEW_LABEL = { open: "Abierta", reviewed: "Revisada", clarification_requested: "Aclaración pedida" } as const;

export const DOC_KIND_LABEL: Record<string, string> = {
  trial_balance: "Sumas y saldos",
  norma43: "Norma 43",
  modelo200: "Modelo 200",
  cuentas_anuales: "Cuentas anuales",
  cirbe: "CIRBE",
  aeat_cert: "Certificado AEAT",
  tgss_cert: "Certificado TGSS",
  borme: "BORME",
  other: "Documento",
};

export const DISCLAIMER = "credIA verifica y organiza la información; no puntúa ni recomienda. La decisión es del prestamista.";

/** Activity (audit log) labels for the Detalles sheet. Unknown actions show their code. */
export const AUDIT_LABEL: Record<string, string> = {
  "case.created": "Caso creado",
  "borrower.invited": "Enlace enviado a la empresa",
  "borrower.link_regenerated": "Nuevo enlace generado",
  "case.viewed_as_borrower": "Vista de la empresa consultada",
  "document.uploaded": "Documento subido",
  "document.requested": "Documento pedido a la empresa",
  "delegate.invited": "Enlace enviado a la gestoría",
  "holded.connected": "Holded conectado",
  "holded.synced": "Holded sincronizado",
  "holded.sync_failed": "Error al sincronizar Holded",
  "holded.token_deleted": "Clave de Holded eliminada",
  "holded.token_discarded": "Clave de Holded descartada",
  "case.submitted": "Documentación enviada",
  "consent.withdrawn": "Consentimiento retirado",
  "support.requested": "La empresa pidió ayuda",
  "pipeline.recomputed": "Datos recalculados",
  "check.reviewed": "Alerta marcada como revisada",
  "check.clarification_requested": "Aclaración pedida",
  "check.open": "Alerta reabierta",
  "package.exported": "Paquete exportado",
  "document.downloaded": "Documento abierto",
  "support.closed": "Petición de ayuda atendida",
  "case.viewed": "Caso consultado",
  "case.tables_viewed": "Tablas completas consultadas",
};

export const ACTOR_LABEL: Record<string, string> = { borrower: "Empresa", delegate: "Gestoría", system: "Sistema" };

/** Canonical statement lines (PGC roll-up), for the full tables and exports. */
export const LINE_LABEL: Record<string, string> = {
  nonCurrentAssets: "Activo no corriente",
  inventories: "Existencias",
  tradeReceivables: "Clientes",
  otherReceivables: "Otros deudores",
  shortTermInvestments: "Inversiones financieras a corto plazo",
  cash: "Tesorería",
  prepayments: "Periodificaciones",
  totalAssets: "Total activo",
  equity: "Patrimonio neto",
  currentYearResultIncluded: "  del que resultado del periodo (sin cerrar)",
  provisions: "Provisiones",
  longTermFinancialDebt: "Deuda financiera a largo plazo",
  longTermOtherLiabilities: "Otros pasivos a largo plazo",
  shortTermFinancialDebt: "Deuda financiera a corto plazo",
  relatedPartyShortTerm: "Deudas con socios y vinculadas",
  tradePayables: "Proveedores",
  otherCurrentLiabilities: "Otros pasivos corrientes",
  totalLiabilities: "Total patrimonio neto y pasivo",
  revenue: "Cifra de negocios",
  otherOperatingIncome: "Otros ingresos de explotación",
  cogs: "Aprovisionamientos",
  personnel: "Gastos de personal",
  externalServices: "Servicios exteriores",
  otherTaxes: "Tributos",
  otherOperatingExpenses: "Otros gastos de explotación",
  grantsTransferred: "Imputación de subvenciones",
  nonRecurringResult: "Resultados excepcionales",
  ebitda: "EBITDA",
  depreciation: "Amortización",
  operatingImpairments: "Deterioros de explotación",
  operatingResult: "Resultado de explotación",
  financialIncome: "Ingresos financieros",
  financialExpense: "Gastos financieros",
  financialImpairments: "Deterioros financieros",
  financialResult: "Resultado financiero",
  preTaxResult: "Resultado antes de impuestos",
  incomeTax: "Impuesto sobre beneficios",
  netIncome: "Resultado del periodo",
};
